export const
  ANIMATION_NAMES = {
    CAR: {
      IDLE: {
        LAND: 'CAR_IDLE_LAND',
        SKY: 'CAR_IDLE_SKY',
        SPACE: 'CAR_IDLE_SPACE',
        WATER: 'CAR_IDLE_WATER'
      },
      FEATURE_IDLE: {
        ATTACK: 'CAR_FEATURE_IDLE_ATTACK',
        DEFENSIVE: 'CAR_FEATURE_IDLE_DEFENSIVE',
        ENGINEERING: 'CAR_FEATURE_IDLE_ENGINEERING',
        POWER: 'CAR_FEATURE_IDLE_POWER'
      }
    },
    CITY: {
      IDLE: {
        LAND: 'CITY_IDLE_LAND',
        SKY: 'CITY_IDLE_SKY',
        SPACE: 'CITY_IDLE_SPACE',
        WATER: 'CITY_IDLE_WATER'
      },
      FEATURE_IDLE: {
        ATTACK: 'CITY_FEATURE_IDLE_ATTACK',
        DEFENSIVE: 'CITY_FEATURE_IDLE_DEFENSIVE',
        ENGINEERING: 'CITY_FEATURE_IDLE_ENGINEERING',
        POWER: 'CITY_FEATURE_IDLE_POWER'
      }
    },
    MECH: {
      IDLE: {
        LAND: 'MECH_IDLE_LAND',
        SKY: 'MECH_IDLE_SKY',
        SPACE: 'MECH_IDLE_SPACE',
        WATER: 'MECH_IDLE_WATER'
      },
      FEATURE_IDLE: {
        ATTACK: 'MECH_FEATURE_IDLE_ATTACK',
        DEFENSIVE: 'MECH_FEATURE_IDLE_DEFENSIVE',
        ENGINEERING: 'MECH_FEATURE_IDLE_ENGINEERING',
        POWER: 'MECH_FEATURE_IDLE_POWER'
      }
    },
    STATION: {
      IDLE: {
        LAND: 'STATION_IDLE_LAND',
        SKY: 'STATION_IDLE_SKY',
        SPACE: 'STATION_IDLE_SPACE',
        WATER: 'STATION_IDLE_WATER'
      },
      FEATURE_IDLE: {
        ATTACK: 'STATION_FEATURE_IDLE_ATTACK',
        DEFENSIVE: 'STATION_FEATURE_IDLE_DEFENSIVE',
        ENGINEERING: 'STATION_FEATURE_IDLE_ENGINEERING',
        POWER: 'STATION_FEATURE_IDLE_POWER'
      }
    }
  }
;
