export const
  AMBITS = {
    LAND: 'LAND',
    SKY: 'SKY',
    SPACE: 'SPACE',
    WATER: 'WATER',
  },
  FEATURES = {
    ATTACK: 'ATTACK_SYSTEM',
    DEFENSIVE: 'DEFENSIVE_SYSTEM',
    ENGINEERING: 'ENGINEERING_SYSTEM',
    POWER: 'POWER_SYSTEM',
    STORAGE: 'STORAGE_SYSTEM'
  },
  CONFIG = {
    INITIAL_HASHRATE: 100000
  };
