export const
  LOTTIE_EVENTS = {
    LOTTIE_CUSTOMIZED: 'LOTTIE_CUSTOMIZED',
    LOTTIE_PLAY: 'LOTTIE_PLAY',
    LOTTIE_STOP: 'LOTTIE_STOP'
  },
  LOTTIE_CUSTOM_EVENTS = {
    LOTTIE_AUTOPLAY: 'LOTTIE_CUSTOM_AUTOPLAY',
  }
;
