import {DroidUI} from "../ui/DroidUI";
import {Navbar} from "./common/Navbar";
import {Footer} from "./common/Footer";

import {Instance} from "../models/Instance";
import {DroidUIWattAmount} from "../ui/components/DroidUIWattAmount";
import {DroidUIWattRank} from "../ui/components/DroidUIWattRank";
import {DroidUIWattAmountTotal} from "../ui/components/DroidUIWattAmountTotal";

const instance = new Instance();
await instance.initActive();

const page = 'schematics';

const navbar = new Navbar(page, { searchEnabled: true, droidHash: instance.address});
navbar.init('nav-wrapper');

const droidUi = new DroidUI();


const urlParams = new URLSearchParams(window.location.search);
const droidId = (urlParams.get('droid_id') === '') ? instance.address : urlParams.get('droid_id');



// rank
const wattRank = new DroidUIWattRank(instance);
await wattRank.init('watt_rank_container');

// load main watt display
const wattAmount = new DroidUIWattAmount(instance);
await wattAmount.init('watt_amount_droid_container');

// load main watt display
const wattAmountTotal = new DroidUIWattAmountTotal(instance);
await wattAmountTotal.init('watt_amount_total_container');





// watt over time


// most watty structure

// watt by structures
// watt generation per block
// watter generated by all structures per block


// send watt
// transaction list


// delegate / undelegate
// claim





const footer = new Footer();
footer.init('footer-wrapper');

const searchHandler = function() {
  const searchString = document.getElementById('nav-search-input').value;
  droidUi.searchAndLoadSchematicsByCreator('schematics-list', searchString, instance.address);
};

document.getElementById('nav-search-btn').addEventListener('click', searchHandler);
document.getElementById('nav-search-input').addEventListener('keypress', (event) => {
  if (event.key === 'Enter') {
    searchHandler(event);
  }
});
